/**
 * English translations
 */
export default {
  // General
  app_name: 'EvokeEssence Crypto',
  ok: 'OK',
  cancel: 'Cancel',
  close: 'Close',
  back: 'Back',
  next: 'Next',
  done: 'Done',
  loading: 'Loading...',
  success: 'Success',
  error: 'Error',
  warning: 'Warning',
  information: 'Information',
  try_again: 'Try Again',
  continue: 'Continue',
  save: 'Save',
  delete: 'Delete',
  confirm: 'Confirm',
  search: 'Search',
  coming_soon: 'Coming Soon',
  
  // Auth
  login: 'Login',
  login_title: 'Welcome back',
  login_subtitle: 'Enter your credentials to access your account',
  register: 'Register',
  register_title: 'Create account',
  register_subtitle: 'Enter your details to create your account',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  confirm_password: 'Confirm Password',
  forgot_password: 'Forgot Password?',
  remember_me: 'Remember Me',
  dont_have_account: "Don't have an account?",
  already_have_account: 'Already have an account?',
  login_with_face_id: 'Login with Face ID',
  login_with_fingerprint: 'Login with Fingerprint',
  login_failed: 'Login failed. Please check your credentials and try again.',
  please_enter_credentials: 'Please enter your username and password.',
  logout: 'Logout',
  logout_confirmation: 'Are you sure you want to log out?',
  
  // Two-factor authentication
  two_factor_title: 'Two-Factor Authentication',
  two_factor_subtitle: 'Enter the verification code from your authenticator app',
  verification_code: 'Verification Code',
  invalid_code: 'Invalid code. Please try again.',
  verify: 'Verify',
  code_sent: 'A verification code has been sent to your email',
  resend_code: 'Resend Code',
  resend_code_in: 'Resend code in {{seconds}}s',
  setup_2fa: 'Set up Two-Factor Authentication',
  setup_2fa_subtitle: 'Scan the QR code with your authenticator app',
  setup_2fa_step_1: '1. Download an authenticator app',
  setup_2fa_step_2: '2. Scan this QR code with the app',
  setup_2fa_step_3: '3. Enter the verification code from the app',
  setup_2fa_manual_key: 'Manual entry key:',
  setup_2fa_success: 'Two-factor authentication has been set up successfully',
  
  // Navigation
  tab_home: 'Home',
  tab_market: 'Market',
  tab_wallet: 'Wallet',
  tab_trading: 'Trading',
  tab_profile: 'Profile',
  
  // Home
  welcome: 'Welcome, {{name}}',
  portfolio_value: 'Portfolio Value',
  assets: 'Assets',
  recent_transactions: 'Recent Transactions',
  price_alerts: 'Price Alerts',
  news: 'News',
  market_overview: 'Market Overview',
  view_all: 'View All',
  set_alert: 'Set Alert',
  read_more: 'Read More',
  
  // Market
  markets: 'Markets',
  trending: 'Trending',
  gainers: 'Gainers',
  losers: 'Losers',
  favorites: 'Favorites',
  search_markets: 'Search markets',
  price: 'Price',
  change_24h: '24h Change',
  market_cap: 'Market Cap',
  volume_24h: '24h Volume',
  high_24h: '24h High',
  low_24h: '24h Low',
  all_time_high: 'All-Time High',
  all_time_low: 'All-Time Low',
  circulating_supply: 'Circulating Supply',
  total_supply: 'Total Supply',
  max_supply: 'Max Supply',
  timeframe_1h: '1H',
  timeframe_1d: '1D',
  timeframe_1w: '1W',
  timeframe_1m: '1M',
  timeframe_1y: '1Y',
  timeframe_all: 'ALL',
  
  // Wallet
  my_assets: 'My Assets',
  total_balance: 'Total Balance',
  available_balance: 'Available Balance',
  send: 'Send',
  receive: 'Receive',
  convert: 'Convert',
  transaction_history: 'Transaction History',
  deposit: 'Deposit',
  withdraw: 'Withdraw',
  deposit_address: 'Deposit Address',
  withdrawal_address: 'Withdrawal Address',
  amount: 'Amount',
  withdrawal_amount: 'Withdrawal Amount',
  transaction_fee: 'Transaction Fee',
  total_amount: 'Total Amount',
  transaction_details: 'Transaction Details',
  transaction_id: 'Transaction ID',
  transaction_status: 'Status',
  transaction_type: 'Type',
  date: 'Date',
  copy_address: 'Copy Address',
  address_copied: 'Address copied to clipboard',
  scan_qr_code: 'Scan QR Code',
  minimum_withdrawal: 'Minimum withdrawal amount is {{amount}}',
  insufficient_funds: 'Insufficient funds',
  confirm_transaction: 'Confirm Transaction',
  transaction_submitted: 'Transaction submitted',
  transaction_confirmed: 'Transaction confirmed',
  transaction_failed: 'Transaction failed',
  
  // Transaction status
  status_pending: 'Pending',
  status_completed: 'Completed',
  status_failed: 'Failed',
  status_cancelled: 'Cancelled',
  type_deposit: 'Deposit',
  type_withdrawal: 'Withdrawal',
  type_convert: 'Convert',
  
  // Trading
  buy: 'Buy',
  sell: 'Sell',
  exchange: 'Exchange',
  market_order: 'Market Order',
  limit_order: 'Limit Order',
  stop_limit: 'Stop Limit',
  from: 'From',
  to: 'To',
  available: 'Available',
  rate: 'Rate',
  order_details: 'Order Details',
  order_submitted: 'Order submitted',
  order_filled: 'Order filled',
  order_partially_filled: 'Order partially filled',
  order_cancelled: 'Order cancelled',
  no_orders: 'No orders',
  open_orders: 'Open Orders',
  order_history: 'Order History',
  order_type: 'Order Type',
  order_status: 'Order Status',
  buy_price: 'Buy Price',
  sell_price: 'Sell Price',
  filled: 'Filled',
  
  // Profile
  profile: 'Profile',
  settings: 'Settings',
  security: 'Security',
  verification: 'Verification',
  referrals: 'Referrals',
  help: 'Help',
  about: 'About',
  terms: 'Terms of Service',
  privacy: 'Privacy Policy',
  language: 'Language',
  currency: 'Currency',
  theme: 'Theme',
  notifications: 'Notifications',
  account_settings: 'Account Settings',
  personal_information: 'Personal Information',
  change_password: 'Change Password',
  full_name: 'Full Name',
  phone_number: 'Phone Number',
  address: 'Address',
  city: 'City',
  zip_code: 'ZIP Code',
  country: 'Country',
  save_changes: 'Save Changes',
  current_password: 'Current Password',
  new_password: 'New Password',
  confirm_new_password: 'Confirm New Password',
  password_changed: 'Password changed successfully',
  
  // Verification/KYC
  kyc_verification: 'Identity Verification',
  kyc_subtitle: 'Complete the verification process to access all features',
  kyc_not_verified: 'Not Verified',
  kyc_pending: 'Verification Pending',
  kyc_verified: 'Verified',
  kyc_rejected: 'Verification Rejected',
  identity_verification: 'Identity Verification',
  address_verification: 'Address Verification',
  identity_document: 'Identity Document',
  proof_of_address: 'Proof of Address',
  selfie: 'Selfie with ID',
  upload_document: 'Upload Document',
  take_photo: 'Take Photo',
  select_document_type: 'Select Document Type',
  passport: 'Passport',
  national_id: 'National ID Card',
  driving_license: 'Driving License',
  residence_permit: 'Residence Permit',
  upload_front: 'Upload Front Side',
  upload_back: 'Upload Back Side',
  upload_selfie: 'Upload Selfie with ID',
  upload_proof_of_address: 'Upload Proof of Address',
  verification_tips: 'Verification Tips',
  verification_tip_1: 'Make sure the document is clearly visible',
  verification_tip_2: 'All corners of the document should be visible',
  verification_tip_3: 'The document should not be expired',
  verification_tip_4: 'Selfie should show your face and ID clearly',
  verification_submitted: 'Verification submitted successfully',
  verification_pending_message: 'Your verification is being processed. This usually takes 1-2 business days.',
  verification_rejected_message: 'Your verification was rejected. Please check the reason and try again.',
  try_again_with_new_documents: 'Try Again with New Documents',
  
  // Referrals
  referral_program: 'Referral Program',
  referral_subtitle: 'Invite friends and earn rewards',
  your_referral_code: 'Your Referral Code',
  referral_link: 'Referral Link',
  copy_code: 'Copy Code',
  share_link: 'Share Link',
  code_copied: 'Code copied to clipboard',
  link_copied: 'Link copied to clipboard',
  referral_rewards: 'Referral Rewards',
  total_referrals: 'Total Referrals',
  active_referrals: 'Active Referrals',
  referral_earnings: 'Referral Earnings',
  pending_rewards: 'Pending Rewards',
  share_message: 'Sign up on EvokeEssence Crypto with my referral code: {{code}} and get a bonus!',
  
  // Contractor dashboard
  contractor_dashboard: 'Contractor Dashboard',
  contractor_statistics: 'Statistics',
  referral_statistics: 'Referral Statistics',
  total_referred_users: 'Total Referred Users',
  total_referred_deposits: 'Total Referred Deposits',
  commission_rate: 'Commission Rate',
  total_commission: 'Total Commission',
  referred_users: 'Referred Users',
  date_joined: 'Date Joined',
  total_deposits: 'Total Deposits',
  commission_earned: 'Commission Earned',
  no_referred_users: 'No referred users yet',
  monthly_statistics: 'Monthly Statistics',
  
  // Admin dashboard
  admin_dashboard: 'Admin Dashboard',
  user_management: 'User Management',
  user_details: 'User Details',
  transaction_management: 'Transaction Management',
  kyc_management: 'KYC Management',
  employee_management: 'Employee Management',
  contractor_management: 'Contractor Management',
  system_settings: 'System Settings',
  user_list: 'User List',
  manage_users: 'Manage Users',
  manage_employees: 'Manage Employees',
  manage_contractors: 'Manage Contractors',
  user_id: 'User ID',
  user_status: 'User Status',
  user_role: 'User Role',
  registration_date: 'Registration Date',
  last_login: 'Last Login',
  user_actions: 'Actions',
  view_user: 'View User',
  edit_user: 'Edit User',
  suspend_user: 'Suspend User',
  activate_user: 'Activate User',
  create_employee: 'Create Employee',
  edit_employee: 'Edit Employee',
  employee_permissions: 'Employee Permissions',
  
  // Biometric authentication
  biometric_authentication: 'Biometric Authentication',
  biometrics_not_available: 'Biometric authentication is not available on this device.',
  biometrics_not_available_message: 'Your device doesn\'t support biometric authentication or no biometrics are enrolled.',
  biometrics_not_available_title: 'Biometrics Not Available',
  biometrics_lockout_message: 'Too many failed attempts. Please use your device passcode to unlock.',
  biometrics_lockout_title: 'Biometrics Locked Out',
  biometrics_cancelled: 'Authentication was cancelled.',
  biometrics_error: 'An error occurred during biometric authentication.',
  biometric_auth_failed: 'Biometric authentication failed. Please try again or use your password.',
  biometric_auth_not_setup: 'Biometric authentication is not set up. Please log in with your password first.',
  authentication_failed: 'Authentication Failed',
  biometrics_prompt_login: 'Authenticate to log in',
  biometrics_prompt_transaction: 'Authenticate to confirm transaction',
  biometrics_prompt_verify: 'Verify your identity',
  biometrics_prompt_authenticate: 'Authenticate to continue',
  enter_passcode: 'Enter passcode',
  face_id_login: 'Login with Face ID',
  fingerprint_login: 'Login with Fingerprint',
  face_id_transaction: 'Authenticate with Face ID',
  fingerprint_transaction: 'Authenticate with Fingerprint',
  face_id_authenticate: 'Authenticate with Face ID',
  fingerprint_authenticate: 'Authenticate with Fingerprint',
  biometrics_login_description: 'Use biometric authentication to quickly and securely log in to your account.',
  biometrics_transaction_description: 'Confirm this transaction using biometric authentication for additional security.',
  biometrics_authenticate_description: 'Verify your identity to continue with this sensitive operation.',
  enable_biometric_auth: 'Enable Biometric Authentication',
  enable_biometric_auth_description: 'Use your fingerprint or face to securely authenticate',
  use_biometrics_at_login: 'Use Biometrics at Login',
  use_biometrics_at_login_description: 'Automatically prompt for biometric authentication when logging in',
  test_biometric_auth: 'Test Biometric Authentication',
  biometrics_subtitle: 'Quick and secure authentication',
  biometrics_info_title: 'About Biometric Authentication',
  biometrics_info_text: 'Biometric authentication provides a faster and more secure way to verify your identity compared to traditional passwords.',
  biometrics_security_benefit: 'Enhanced security with unique biometric data',
  biometrics_convenience_benefit: 'Faster login without typing passwords',
  biometrics_privacy_benefit: 'Your biometric data never leaves your device',
  biometrics_enabled_title: 'Biometrics Enabled',
  biometrics_enabled_message: 'Biometric authentication has been successfully enabled.',
  biometrics_disabled_title: 'Biometrics Disabled',
  biometrics_disabled_message: 'Biometric authentication has been disabled.',
  biometrics_test_success_title: 'Authentication Successful',
  biometrics_test_success_message: 'Biometric authentication is working correctly.',
  biometrics_test_error: 'Failed to test biometric authentication. Please try again.',
  
  // Notifications
  push_notifications: 'Push Notifications',
  email_notifications: 'Email Notifications',
  price_alerts_notifications: 'Price Alerts',
  transaction_notifications: 'Transactions',
  security_notifications: 'Security Alerts',
  news_notifications: 'News & Updates',
  marketing_notifications: 'Marketing',
  
  // Errors and warnings
  no_internet_connection: 'No internet connection',
  try_again_later: 'Please try again later',
  session_expired: 'Your session has expired. Please log in again.',
  unexpected_error: 'An unexpected error occurred. Please try again.',
  form_error: 'Please fix the errors in the form.',
  required_field: 'This field is required.',
  invalid_email: 'Please enter a valid email address.',
  password_mismatch: 'Passwords do not match.',
  password_too_short: 'Password must be at least {{length}} characters long.',
  invalid_code: 'Invalid code. Please try again.',
  server_error: 'Server error. Please try again later.',
  network_error: 'Network error. Please check your connection and try again.',
};